// Function catalog: argument hints, descriptions and categories for autocomplete and Insert Function.

export interface FnInfo {
  name: string;
  args: string;
  desc: string;
  cat: string;
}

const RAW: [string, string, string, string][] = [
  // [category, name, args, description]
  ['Math & Trig', 'SUM', 'number1, [number2], ...', 'Adds all the numbers in a range of cells.'],
  ['Math & Trig', 'SUMIF', 'range, criteria, [sum_range]', 'Adds the cells specified by a given condition or criteria.'],
  ['Math & Trig', 'SUMIFS', 'sum_range, criteria_range1, criteria1, ...', 'Adds the cells specified by a given set of conditions or criteria.'],
  ['Math & Trig', 'SUMPRODUCT', 'array1, [array2], ...', 'Returns the sum of the products of corresponding ranges or arrays.'],
  ['Math & Trig', 'SUMSQ', 'number1, [number2], ...', 'Returns the sum of the squares of the arguments.'],
  ['Math & Trig', 'ABS', 'number', 'Returns the absolute value of a number.'],
  ['Math & Trig', 'ROUND', 'number, num_digits', 'Rounds a number to a specified number of digits.'],
  ['Math & Trig', 'ROUNDUP', 'number, num_digits', 'Rounds a number up, away from zero.'],
  ['Math & Trig', 'ROUNDDOWN', 'number, num_digits', 'Rounds a number down, toward zero.'],
  ['Math & Trig', 'INT', 'number', 'Rounds a number down to the nearest integer.'],
  ['Math & Trig', 'TRUNC', 'number, [num_digits]', 'Truncates a number to an integer.'],
  ['Math & Trig', 'MOD', 'number, divisor', 'Returns the remainder after a number is divided by a divisor.'],
  ['Math & Trig', 'POWER', 'number, power', 'Returns the result of a number raised to a power.'],
  ['Math & Trig', 'SQRT', 'number', 'Returns the square root of a number.'],
  ['Math & Trig', 'PRODUCT', 'number1, [number2], ...', 'Multiplies all the numbers given as arguments.'],
  ['Math & Trig', 'CEILING', 'number, significance', 'Rounds a number up to the nearest multiple of significance.'],
  ['Math & Trig', 'FLOOR', 'number, significance', 'Rounds a number down to the nearest multiple of significance.'],
  ['Math & Trig', 'MROUND', 'number, multiple', 'Returns a number rounded to the desired multiple.'],
  ['Math & Trig', 'RAND', '', 'Returns a random number greater than or equal to 0 and less than 1.'],
  ['Math & Trig', 'RANDBETWEEN', 'bottom, top', 'Returns a random number between the numbers you specify.'],
  ['Math & Trig', 'PI', '', 'Returns the value of pi.'],
  ['Math & Trig', 'EXP', 'number', 'Returns e raised to the power of a given number.'],
  ['Math & Trig', 'LN', 'number', 'Returns the natural logarithm of a number.'],
  ['Math & Trig', 'LOG', 'number, [base]', 'Returns the logarithm of a number to the base you specify.'],
  ['Math & Trig', 'LOG10', 'number', 'Returns the base-10 logarithm of a number.'],
  ['Math & Trig', 'SIN', 'number', 'Returns the sine of an angle.'],
  ['Math & Trig', 'COS', 'number', 'Returns the cosine of an angle.'],
  ['Math & Trig', 'TAN', 'number', 'Returns the tangent of an angle.'],
  ['Math & Trig', 'RADIANS', 'angle', 'Converts degrees to radians.'],
  ['Math & Trig', 'DEGREES', 'angle', 'Converts radians to degrees.'],
  ['Math & Trig', 'SIGN', 'number', 'Returns the sign of a number.'],
  ['Math & Trig', 'EVEN', 'number', 'Rounds a number up to the nearest even integer.'],
  ['Math & Trig', 'ODD', 'number', 'Rounds a number up to the nearest odd integer.'],
  ['Math & Trig', 'FACT', 'number', 'Returns the factorial of a number.'],
  ['Math & Trig', 'GCD', 'number1, [number2], ...', 'Returns the greatest common divisor.'],
  ['Math & Trig', 'LCM', 'number1, [number2], ...', 'Returns the least common multiple.'],
  ['Math & Trig', 'SUBTOTAL', 'function_num, ref1, ...', 'Returns a subtotal in a list or database.'],
  ['Math & Trig', 'AGGREGATE', 'function_num, options, ref1, ...', 'Returns an aggregate in a list or database.'],
  ['Math & Trig', 'COMBIN', 'number, number_chosen', 'Returns the number of combinations for a given number of items.'],
  ['Math & Trig', 'MMULT', 'array1, array2', 'Returns the matrix product of two arrays.'],
  ['Math & Trig', 'SEQUENCE', 'rows, [columns], [start], [step]', 'Generates a list of sequential numbers.'],
  ['Statistical', 'AVERAGE', 'number1, [number2], ...', 'Returns the average (arithmetic mean) of its arguments.'],
  ['Statistical', 'AVERAGEIF', 'range, criteria, [average_range]', 'Finds average for the cells specified by a given condition.'],
  ['Statistical', 'AVERAGEIFS', 'average_range, criteria_range1, criteria1, ...', 'Finds average for the cells specified by a given set of conditions.'],
  ['Statistical', 'AVERAGEA', 'value1, [value2], ...', 'Returns the average of its arguments, including text and logical values.'],
  ['Statistical', 'COUNT', 'value1, [value2], ...', 'Counts the number of cells in a range that contain numbers.'],
  ['Statistical', 'COUNTA', 'value1, [value2], ...', 'Counts the number of cells in a range that are not empty.'],
  ['Statistical', 'COUNTBLANK', 'range', 'Counts the number of empty cells in a specified range.'],
  ['Statistical', 'COUNTIF', 'range, criteria', 'Counts the number of cells within a range that meet the given condition.'],
  ['Statistical', 'COUNTIFS', 'criteria_range1, criteria1, ...', 'Counts the number of cells specified by a given set of conditions.'],
  ['Statistical', 'MAX', 'number1, [number2], ...', 'Returns the largest value in a set of values.'],
  ['Statistical', 'MIN', 'number1, [number2], ...', 'Returns the smallest value in a set of values.'],
  ['Statistical', 'MAXIFS', 'max_range, criteria_range1, criteria1, ...', 'Returns the maximum value among cells specified by conditions.'],
  ['Statistical', 'MINIFS', 'min_range, criteria_range1, criteria1, ...', 'Returns the minimum value among cells specified by conditions.'],
  ['Statistical', 'MEDIAN', 'number1, [number2], ...', 'Returns the median of the given numbers.'],
  ['Statistical', 'MODE', 'number1, [number2], ...', 'Returns the most frequently occurring value.'],
  ['Statistical', 'LARGE', 'array, k', 'Returns the k-th largest value in a data set.'],
  ['Statistical', 'SMALL', 'array, k', 'Returns the k-th smallest value in a data set.'],
  ['Statistical', 'RANK', 'number, ref, [order]', 'Returns the rank of a number in a list of numbers.'],
  ['Statistical', 'STDEV', 'number1, [number2], ...', 'Estimates standard deviation based on a sample.'],
  ['Statistical', 'STDEV.S', 'number1, [number2], ...', 'Estimates standard deviation based on a sample.'],
  ['Statistical', 'STDEV.P', 'number1, [number2], ...', 'Calculates standard deviation based on the entire population.'],
  ['Statistical', 'VAR', 'number1, [number2], ...', 'Estimates variance based on a sample.'],
  ['Statistical', 'VAR.S', 'number1, [number2], ...', 'Estimates variance based on a sample.'],
  ['Statistical', 'VAR.P', 'number1, [number2], ...', 'Calculates variance based on the entire population.'],
  ['Statistical', 'PERCENTILE', 'array, k', 'Returns the k-th percentile of values in a range.'],
  ['Statistical', 'QUARTILE', 'array, quart', 'Returns the quartile of a data set.'],
  ['Statistical', 'CORREL', 'array1, array2', 'Returns the correlation coefficient between two data sets.'],
  ['Statistical', 'FORECAST', 'x, known_ys, known_xs', 'Calculates a future value by using existing values.'],
  ['Statistical', 'SLOPE', "known_ys, known_xs", 'Returns the slope of the linear regression line.'],
  ['Statistical', 'INTERCEPT', "known_ys, known_xs", 'Returns the intercept of the linear regression line.'],
  ['Statistical', 'NORM.DIST', 'x, mean, standard_dev, cumulative', 'Returns the normal distribution.'],
  ['Lookup & Reference', 'VLOOKUP', 'lookup_value, table_array, col_index_num, [range_lookup]', 'Looks for a value in the leftmost column of a table, and returns a value in the same row from a column you specify.'],
  ['Lookup & Reference', 'HLOOKUP', 'lookup_value, table_array, row_index_num, [range_lookup]', 'Looks for a value in the top row of a table and returns the value in the same column from a row you specify.'],
  ['Lookup & Reference', 'XLOOKUP', 'lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]', 'Searches a range or an array for a match and returns the corresponding item.'],
  ['Lookup & Reference', 'LOOKUP', 'lookup_value, lookup_vector, [result_vector]', 'Looks up a value either from a one-row or one-column range.'],
  ['Lookup & Reference', 'INDEX', 'array, row_num, [column_num]', 'Returns a value or reference of the cell at the intersection of a particular row and column.'],
  ['Lookup & Reference', 'MATCH', 'lookup_value, lookup_array, [match_type]', 'Returns the relative position of an item in an array.'],
  ['Lookup & Reference', 'CHOOSE', 'index_num, value1, [value2], ...', 'Chooses a value from a list of values.'],
  ['Lookup & Reference', 'OFFSET', 'reference, rows, cols, [height], [width]', 'Returns a reference offset from a given reference.'],
  ['Lookup & Reference', 'INDIRECT', 'ref_text, [a1]', 'Returns the reference specified by a text string.'],
  ['Lookup & Reference', 'ROW', '[reference]', 'Returns the row number of a reference.'],
  ['Lookup & Reference', 'COLUMN', '[reference]', 'Returns the column number of a reference.'],
  ['Lookup & Reference', 'ROWS', 'array', 'Returns the number of rows in a reference or array.'],
  ['Lookup & Reference', 'COLUMNS', 'array', 'Returns the number of columns in a reference or array.'],
  ['Lookup & Reference', 'ADDRESS', 'row_num, column_num, [abs_num], [a1], [sheet_text]', 'Creates a cell reference as text.'],
  ['Lookup & Reference', 'TRANSPOSE', 'array', 'Converts a vertical range of cells to a horizontal range, or vice versa.'],
  ['Lookup & Reference', 'HYPERLINK', 'link_location, [friendly_name]', 'Creates a shortcut that opens a document or web page.'],
  ['Lookup & Reference', 'FILTER', 'array, include, [if_empty]', 'Filters a range of data based on criteria you define.'],
  ['Lookup & Reference', 'SORT', 'array, [sort_index], [sort_order], [by_col]', 'Sorts the contents of a range or array.'],
  ['Lookup & Reference', 'UNIQUE', 'array, [by_col], [exactly_once]', 'Returns the unique values from a range or array.'],
  ['Logical', 'IF', 'logical_test, [value_if_true], [value_if_false]', 'Checks whether a condition is met, and returns one value if TRUE, and another value if FALSE.'],
  ['Logical', 'IFS', 'logical_test1, value_if_true1, ...', 'Checks whether one or more conditions are met and returns a value corresponding to the first TRUE condition.'],
  ['Logical', 'IFERROR', 'value, value_if_error', 'Returns value_if_error if expression is an error and the value of the expression itself otherwise.'],
  ['Logical', 'IFNA', 'value, value_if_na', 'Returns the value you specify if the expression resolves to #N/A.'],
  ['Logical', 'AND', 'logical1, [logical2], ...', 'Checks whether all arguments are TRUE.'],
  ['Logical', 'OR', 'logical1, [logical2], ...', 'Checks whether any of the arguments are TRUE.'],
  ['Logical', 'NOT', 'logical', 'Changes FALSE to TRUE, or TRUE to FALSE.'],
  ['Logical', 'XOR', 'logical1, [logical2], ...', 'Returns a logical Exclusive Or of all arguments.'],
  ['Logical', 'SWITCH', 'expression, value1, result1, [default_or_value2], ...', 'Evaluates an expression against a list of values and returns the result corresponding to the first match.'],
  ['Logical', 'TRUE', '', 'Returns the logical value TRUE.'],
  ['Logical', 'FALSE', '', 'Returns the logical value FALSE.'],
  ['Text', 'CONCATENATE', 'text1, [text2], ...', 'Joins several text strings into one text string.'],
  ['Text', 'CONCAT', 'text1, [text2], ...', 'Concatenates a list or range of text strings.'],
  ['Text', 'TEXTJOIN', 'delimiter, ignore_empty, text1, ...', 'Concatenates text with a delimiter.'],
  ['Text', 'LEFT', 'text, [num_chars]', 'Returns the specified number of characters from the start of a text string.'],
  ['Text', 'RIGHT', 'text, [num_chars]', 'Returns the specified number of characters from the end of a text string.'],
  ['Text', 'MID', 'text, start_num, num_chars', 'Returns the characters from the middle of a text string.'],
  ['Text', 'LEN', 'text', 'Returns the number of characters in a text string.'],
  ['Text', 'LOWER', 'text', 'Converts all letters in a text string to lowercase.'],
  ['Text', 'UPPER', 'text', 'Converts a text string to all uppercase letters.'],
  ['Text', 'PROPER', 'text', 'Converts a text string to proper case.'],
  ['Text', 'TRIM', 'text', 'Removes all spaces from a text string except for single spaces between words.'],
  ['Text', 'CLEAN', 'text', 'Removes all nonprintable characters from text.'],
  ['Text', 'SUBSTITUTE', 'text, old_text, new_text, [instance_num]', 'Replaces existing text with new text in a text string.'],
  ['Text', 'REPLACE', 'old_text, start_num, num_chars, new_text', 'Replaces part of a text string with a different text string.'],
  ['Text', 'FIND', 'find_text, within_text, [start_num]', 'Returns the starting position of one text string within another (case-sensitive).'],
  ['Text', 'SEARCH', 'find_text, within_text, [start_num]', 'Returns the number of the character at which a specific character or text string is first found.'],
  ['Text', 'TEXT', 'value, format_text', 'Converts a value to text in a specific number format.'],
  ['Text', 'VALUE', 'text', 'Converts a text string that represents a number to a number.'],
  ['Text', 'REPT', 'text, number_times', 'Repeats text a given number of times.'],
  ['Text', 'EXACT', 'text1, text2', 'Checks whether two text strings are exactly the same.'],
  ['Text', 'CHAR', 'number', 'Returns the character specified by the code number.'],
  ['Text', 'CODE', 'text', 'Returns a numeric code for the first character in a text string.'],
  ['Text', 'FIXED', 'number, [decimals], [no_commas]', 'Rounds a number to the specified number of decimals and returns the result as text.'],
  ['Text', 'T', 'value', 'Checks whether a value is text, and returns the text if it is.'],
  ['Text', 'UNICHAR', 'number', 'Returns the Unicode character referenced by the given numeric value.'],
  ['Date & Time', 'TODAY', '', 'Returns the current date formatted as a date.'],
  ['Date & Time', 'NOW', '', 'Returns the current date and time formatted as a date and time.'],
  ['Date & Time', 'DATE', 'year, month, day', 'Returns the number that represents the date.'],
  ['Date & Time', 'TIME', 'hour, minute, second', 'Converts hours, minutes and seconds given as numbers to a serial number.'],
  ['Date & Time', 'YEAR', 'serial_number', 'Returns the year of a date.'],
  ['Date & Time', 'MONTH', 'serial_number', 'Returns the month, a number from 1 (January) to 12 (December).'],
  ['Date & Time', 'DAY', 'serial_number', 'Returns the day of the month, a number from 1 to 31.'],
  ['Date & Time', 'HOUR', 'serial_number', 'Returns the hour as a number from 0 to 23.'],
  ['Date & Time', 'MINUTE', 'serial_number', 'Returns the minute, a number from 0 to 59.'],
  ['Date & Time', 'SECOND', 'serial_number', 'Returns the second, a number from 0 to 59.'],
  ['Date & Time', 'WEEKDAY', 'serial_number, [return_type]', 'Returns a number from 1 to 7 identifying the day of the week of a date.'],
  ['Date & Time', 'WEEKNUM', 'serial_number, [return_type]', 'Returns the week number in the year.'],
  ['Date & Time', 'EDATE', 'start_date, months', 'Returns the serial number of the date that is the indicated number of months before or after the start date.'],
  ['Date & Time', 'EOMONTH', 'start_date, months', 'Returns the serial number of the last day of the month before or after a specified number of months.'],
  ['Date & Time', 'DATEDIF', 'start_date, end_date, unit', 'Calculates the number of days, months, or years between two dates.'],
  ['Date & Time', 'DATEVALUE', 'date_text', 'Converts a date in the form of text to a serial number.'],
  ['Date & Time', 'TIMEVALUE', 'time_text', 'Converts a text time to a serial number.'],
  ['Date & Time', 'NETWORKDAYS', 'start_date, end_date, [holidays]', 'Returns the number of whole workdays between two dates.'],
  ['Date & Time', 'WORKDAY', 'start_date, days, [holidays]', 'Returns the serial number of the date before or after a specified number of workdays.'],
  ['Date & Time', 'DAYS', 'end_date, start_date', 'Returns the number of days between two dates.'],
  ['Date & Time', 'YEARFRAC', 'start_date, end_date, [basis]', 'Returns the year fraction representing the number of whole days between two dates.'],
  ['Financial', 'PMT', 'rate, nper, pv, [fv], [type]', 'Calculates the payment for a loan based on constant payments and a constant interest rate.'],
  ['Financial', 'PV', 'rate, nper, pmt, [fv], [type]', 'Returns the present value of an investment.'],
  ['Financial', 'FV', 'rate, nper, pmt, [pv], [type]', 'Returns the future value of an investment.'],
  ['Financial', 'NPV', 'rate, value1, [value2], ...', 'Returns the net present value of an investment.'],
  ['Financial', 'IRR', 'values, [guess]', 'Returns the internal rate of return for a series of cash flows.'],
  ['Financial', 'RATE', 'nper, pmt, pv, [fv], [type], [guess]', 'Returns the interest rate per period of a loan or an investment.'],
  ['Financial', 'NPER', 'rate, pmt, pv, [fv], [type]', 'Returns the number of periods for an investment.'],
  ['Financial', 'IPMT', 'rate, per, nper, pv, [fv], [type]', 'Returns the interest payment for a given period.'],
  ['Financial', 'PPMT', 'rate, per, nper, pv, [fv], [type]', 'Returns the payment on the principal for a given period.'],
  ['Financial', 'XNPV', 'rate, values, dates', 'Returns the net present value for a schedule of cash flows.'],
  ['Financial', 'SLN', 'cost, salvage, life', 'Returns the straight-line depreciation of an asset for one period.'],
  ['Financial', 'DB', 'cost, salvage, life, period, [month]', 'Returns the depreciation of an asset using the fixed-declining balance method.'],
  ['Information', 'ISBLANK', 'value', 'Checks whether a reference is to an empty cell.'],
  ['Information', 'ISERROR', 'value', 'Checks whether a value is an error.'],
  ['Information', 'ISNA', 'value', 'Checks whether a value is #N/A.'],
  ['Information', 'ISNUMBER', 'value', 'Checks whether a value is a number.'],
  ['Information', 'ISTEXT', 'value', 'Checks whether a value is text.'],
  ['Information', 'ISLOGICAL', 'value', 'Checks whether a value is a logical value.'],
  ['Information', 'ISEVEN', 'number', 'Returns TRUE if the number is even.'],
  ['Information', 'ISODD', 'number', 'Returns TRUE if the number is odd.'],
  ['Information', 'ISFORMULA', 'reference', 'Checks whether a reference is to a cell containing a formula.'],
  ['Information', 'NA', '', 'Returns the error value #N/A.'],
  ['Information', 'N', 'value', 'Converts a non-number value to a number.'],
  ['Information', 'TYPE', 'value', 'Returns an integer representing the data type of a value.'],
  ['Information', 'SHEET', '[value]', 'Returns the sheet number of the referenced sheet.'],
  ['Information', 'SHEETS', '[reference]', 'Returns the number of sheets in a reference.'],
  ['Information', 'FORMULATEXT', 'reference', 'Returns a formula as a string.'],
  ['Engineering', 'CONVERT', 'number, from_unit, to_unit', 'Converts a number from one measurement system to another.'],
  ['Engineering', 'DEC2BIN', 'number, [places]', 'Converts a decimal number to binary.'],
  ['Engineering', 'BIN2DEC', 'number', 'Converts a binary number to decimal.'],
  ['Engineering', 'DEC2HEX', 'number, [places]', 'Converts a decimal number to hexadecimal.'],
  ['Engineering', 'HEX2DEC', 'number', 'Converts a hexadecimal number to decimal.'],
  ['Database', 'DSUM', 'database, field, criteria', 'Adds the numbers in the field column of records in the database that match the conditions you specify.'],
  ['Database', 'DAVERAGE', 'database, field, criteria', 'Averages the values in a column in a list or database that match conditions you specify.'],
  ['Database', 'DCOUNT', 'database, field, criteria', 'Counts the cells that contain numbers in the field of records that match the conditions.'],
];

let catalog: Map<string, FnInfo> | null = null;

export function fnCatalog(): Map<string, FnInfo> {
  if (!catalog) {
    catalog = new Map();
    for (const [cat, name, args, desc] of RAW) catalog.set(name, { name, args, desc, cat });
  }
  return catalog;
}

export function fnInfo(name: string): FnInfo {
  return fnCatalog().get(name.toUpperCase()) ?? { name: name.toUpperCase(), args: '...', desc: '', cat: 'All' };
}

export const FN_CATEGORIES = ['Most Recently Used', 'All', 'Financial', 'Date & Time', 'Math & Trig', 'Statistical', 'Lookup & Reference', 'Database', 'Text', 'Logical', 'Information', 'Engineering'];

/** Split an args signature into individual argument labels. */
export function argList(args: string): string[] {
  return args ? args.split(',').map((s) => s.trim()).filter(Boolean) : [];
}
