import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 860 } });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e.stack || e)));
await page.goto('http://localhost:3100/');
await page.waitForFunction(() => window.__myexcel && window.__myexcel.charts);
await page.evaluate(() => {
  const X = window.__myexcel; const sh = () => X.S().wb.activeSheet;
  const put = (r, c, t) => X.store.transact('t', (tx) => X.edit.writeInput(tx, sh(), r, c, t));
  put(0, 0, 'Month'); put(0, 1, 'Revenue'); put(0, 2, 'Cost');
  ['Jan','Feb','Mar','Apr','May','Jun'].forEach((m, i) => { put(i + 1, 0, m); put(i + 1, 1, String(100 + i * 25)); put(i + 1, 2, String(80 + i * 10)); });
  X.store.setState({ sel: { ranges: [{ r1: 0, c1: 0, r2: 6, c2: 2 }], active: { r: 0, c: 0 }, anchor: { r: 0, c: 0 } } });
  X.charts.insertChart('lineMarkers');
  X.store.transact('ps', (tx) => tx.setMeta(sh(), 'pageSetup', { ...sh().pageSetup, gridlines: true, header: { left: '', center: '&A', right: '' }, footer: { left: '', center: 'Page &P of &N', right: '' } }));
  X.store.openDialog('print');
});
await page.waitForTimeout(1500);
await page.screenshot({ path: 'screenshots/print.png' });
if (errors.length) console.log('ERRORS\n' + errors.join('\n'));
await browser.close();
